src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Originating_LineItem_ID__c</fullName>
        <description>Originating LineItem from where this Asset is created first</description>
        <inlineHelpText>Originating LineItem from where this Asset is created first</inlineHelpText>
        <label>Originating LineItem ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets (Renewal Opportunity)</relationshipLabel>
        <relationshipName>Assets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Base_Line_Amount__c</fullName>
        <inlineHelpText>Total amount that can be renewed based on customers previous purchase and contract.Actual Opp amount may differ at the time of closing.If the amount is higher the difference is calculated as upgrade amount and if lower, the difference is downgrade amount.</inlineHelpText>
        <label>Base Line Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Co_Term_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Original opp with which products from these opp are co-termed.</description>
        <inlineHelpText>Original sales opportunity with which products on this opportunity should be co-termed.</inlineHelpText>
        <label>Co-Term With</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>CoTermOpp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to an Originating Opportunity for Renewal Opportunity</description>
        <inlineHelpText>Original sales opportunity that was the basis for the renewal opportunity</inlineHelpText>
        <label>Originating Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Originating Opportunity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset of this line item</description>
        <inlineHelpText>Asset of this line item</inlineHelpText>
        <label>Asset tied to this line item</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entitlement_Term__c</fullName>
        <description>Enter entitlement term</description>
        <inlineHelpText>Enter entitlement term</inlineHelpText>
        <label>Entitlement Term (Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_LineItem_ID__c</fullName>
        <label>Originating Opportunity LineItem ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Originating Source Opportunity ID from where renewal opportunity was created. This is to be used while updating renewal opp when source opp is updated. Example, renewal opp had 50 quantities on certain product from source opp and later on source opp got updated to 55 quantities of same product. This field will allow to update renewal opp easily.</description>
        <label>Originating Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Entitlement_Term_Set_Up__c</fullName>
        <formula>PricebookEntry.Product2.Renewal_Term_Months__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Entitlement Term Set-Up</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price_Per_Unit_Per_Ent_Term__c</fullName>
        <description>Sales Price Per Unit Per Entitlement Term</description>
        <formula>UnitPrice / (Entitlement_Term__c / PricebookEntry.Product2.Renewal_Term_Months__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Price Per Unit Per Ent Term</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Renewal_App_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If your organization is using asset while verifying entitlements in support cases then check this box to auto convert products on &apos;closed won&apos; opportunities into Asset. Default status on converted asset will be &apos;shipped&apos;.</description>
        <inlineHelpText>If your organization is using asset while verifying entitlements in support cases then check this box to auto convert products on &apos;closed won&apos; opportunities into Asset. Default status on converted asset will be &apos;shipped&apos;.</inlineHelpText>
        <label>Convert Product into Asset of Won Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Competitors_Related_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Competitor Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Competitor Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Competitors Related List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Contact_Roles__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Contact Roles Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Contact Roles Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Contact Roles</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Opp_Team_Related_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Opportunity Team Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Opportunity Team Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Opp Team Related List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Field_To_Not_Copy_on_Renewal__c</fullName>
        <description>Select the fields that need not be copied while Opportunity is cloned to create Renewal Opp.</description>
        <inlineHelpText>Select the fields that need not be copied while Opportunity is cloned to create Renewal Opp.</inlineHelpText>
        <label>Opportunity Field To Not Copy on Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>null</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Fields_To_Not_Copy__c</fullName>
        <description>Select the fields that need not be copied while Opportunity Products of source opportunity are cloned to create Renewal Opp.</description>
        <inlineHelpText>Select the fields that need not be copied while Opportunity Products of source opportunity are cloned to create Renewal Opp.</inlineHelpText>
        <label>Opportunity Product Fields To Not Copy</label>
        <picklist>
            <picklistValues>
                <fullName>null</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Prefix_for_Renewal_Opportunity_Name__c</fullName>
        <defaultValue>&quot;Renewal&quot;</defaultValue>
        <description>Sufffix for Renewal Opportunity. Original source opportunity would be suffixed with text entered here to create opportunity name of Renewal Opportunity. E.g. Text entered in this field is &apos;Renewal &apos; and name of original source opportunity is &apos;Software Support Purchase&apos; then name of Renewal Opportunity would be &apos;Software Support Purchase : Renewal - 10/2013&apos;. 10/2013 indicates month and year renewal is due.</description>
        <inlineHelpText>Original source opp would be suffixed with text entered here to create opportunity name of Renewal Opportunity.</inlineHelpText>
        <label>Suffix for Renewal Opportunity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Owner__c</fullName>
        <description>Pick to whom Renewal Opportunity should be assigned.</description>
        <inlineHelpText>Pick to whom Renewal Opportunity should be assigned.</inlineHelpText>
        <label>Renewal Opportunity Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Same as Source Opportunity Owner</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Account Owner of Acct tied to Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A specific User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Type__c</fullName>
        <description>A &apos;Type&apos; field&apos;s value of the Renewal Opportunity.
Must be equal to one of the picklist values of the &apos;Type&apos; field of opportunity</description>
        <inlineHelpText>A Type field&apos;s value of the Renewal Opportunity.
Must be equal to one of the picklist values of the &apos;Type&apos; field of opportunity
Normal value is &apos;Existing Customer - Renewal&apos;</inlineHelpText>
        <label>Renewal Opportunity Type</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Stage__c</fullName>
        <description>First default stage of the Renewal Opportunity.
Normally is &apos;Prospecting&apos;. Picklist is ordered in ascending default probability of stage.</description>
        <inlineHelpText>First default stage of the Renewal Opportunity.
Normally is &apos;Prospecting&apos;. Picklist is ordered in ascending default probability of stage.</inlineHelpText>
        <label>Renewal Opportunity Default Stage</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pick the user to whom Renewals should get assigned.</description>
        <inlineHelpText>Pick the user to whom Renewals should get assigned.</inlineHelpText>
        <label>Assign Renewal to</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Renewal_App_Set</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal App Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Renewal App Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal App Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Source_Opp_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Renewal_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source/Renewal Opp</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal/Source Opp Mappings</relationshipLabel>
        <relationshipName>Renewal_Opp_Mappings_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Opp</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Source/Renewal Opp Mappings</relationshipLabel>
        <relationshipName>Source_Opp_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Source/Renewal Opp Mapping</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Source Opp Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source/Renewal Opp Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
/**
 * Copyright (c) 2014 Comity Designs
 * All rights reserved.
 *
 * This class is an Opportunity trigger handler class for the Renewal Manager.
 *
 * History:
 * =========================================
 * Developer         Date        description
 * --------------------------------------------------------------------------------------------------
 * Ivan Melnikov     07/30/2014  Code refactoring 
 *
 * 
 **/
public with sharing class OpportunityTriggerHandler {
    public static void opportunityAfterUpdateHandler(List<Opportunity> newOpptyList, Map<Id, Opportunity> oldOpptyMap) {
        Map<ID, Opportunity> actionableOpptyDetailsMap = null;
        try {
            Map<String, OpportunityRenewalWrapper> opptyRenewalWrapperMap = new Map<String, OpportunityRenewalWrapper>();
            Map<String,Opportunity> renewedOpptyMap   = new Map<String,Opportunity>();
            List<OpportunityLineItem> renewedOpptyProductList   = new List<OpportunityLineItem>();
            List<Source_Opp_Mapping__c> sourceRenewedOpptyMappingList= new List<Source_Opp_Mapping__c>();
            Set<ID> renewableOpptysAccountSet = new Set<ID>(); 

            /* Retrieve Renewal_App_Setup details. There will be only one record in this object */
            //Read asset and entitlement creation flag setting as well in below query
            //modified to include Renewal_Record_Type_Name__c so that record type can be found based on this.
            List<Renewal_App_Setup__c> rAppSetupList = [
                SELECT r.ID, r.Prefix_for_Renewal_Opportunity_Name__c, r.Renewal_Stage__c, r.Renewal_Opportunity_Type__c, r.Asset__c, 
                    r.Opportunity_Field_To_Not_Copy_on_Renewal__c, r.Opportunity_Product_Fields_To_Not_Copy__c, r.Renewal_Opportunity_Owner__c, 
                    r.User__c, Clone_Competitors_Related_List__c, Clone_Contact_Roles__c, Clone_Opp_Team_Related_List__c 
                FROM Renewal_App_Setup__c r
                LIMIT :Limits.getLimitQueryRows()
            ];

            Renewal_App_Setup__c rAppSetup;
            if (rAppSetupList == null || rAppSetupList.size() != 1) {
                System.debug('~~~0. Error:- Renewal_App_Setup has no/many records...');
                return;
            } else {
                rAppSetup = rAppSetupList[0];
            }

                          
            //Step-10: Put all actionable Opportunity-ID's in map for bulk process. check where opp status has changed to 'closedwon' or not
            //Step-20.1 Retrieve all actionable Opportunities details and put them in map for bulk process. 
            /*Creating a map of all actionable opportunity line items when opportunity stage has changed to 'closedwon'
            Below map stores all opportunity line items of source opportunity where product tied to source opportunity line item
            is renewable based on looking at set-up of that product in Product2 object */
            actionableOpptyDetailsMap = OpportunityRenewalHelper.getActionableOpptyDetailsMap(newOpptyList, 
                oldOpptyMap, rAppSetup.Opportunity_Field_To_Not_Copy_on_Renewal__c, rAppSetup.Opportunity_Product_Fields_To_Not_Copy__c);
            
            if (actionableOpptyDetailsMap == null || actionableOpptyDetailsMap.size()==0) { 
                System.debug(LoggingLevel.INFO,'\n\n~~~:- actionableOpptyDetailsMap has no records...');
                return; 
            }

            /*Get all the useful product-ID's and A/c ID's */     
            //Step-20.2: Retrieve all the useful Renewable product-details from source opportunity
            //Creating map of all renewal products to use in renewal opportunity line items based on set-up of products on
            //source opportunity line item. Also creating map of account ids from source opportunity
            Set<ID> assetIdSet = new Set<ID>();
            Map<ID, Product2> product2Map = OpportunityRenewalHelper.getProductDetailsMapSetAccountID(
                actionableOpptyDetailsMap.values(), renewableOpptysAccountSet, assetIdSet);
            if (product2Map == null || product2Map.size()==0) {
                System.debug(LoggingLevel.INFO,'\n\n~~~:- product2Map has no records...');
                return;        
            }

            //Read source opportunity account info such as acct owner, acct type, acct shipping country
            Map<ID, Account> renewableOpptysAccountMap = new Map<ID, Account>([
                SELECT a.OwnerId, a.Id, a.Type, a.ShippingCountry 
                FROM Account a 
                WHERE a.id in :renewableOpptysAccountSet
            ]);
            Map<ID, Asset> availableAssetObjMap = new Map<ID, Asset>();
            if (assetIdSet.size() > 0) {
                availableAssetObjMap = new Map<ID, Asset>([
                    SELECT Id, Quantity 
                    FROM Asset 
                    WHERE Id IN :assetIdSet 
                ]);
            }

            //START: - Data setup for bulk process, 
            Integer iCount = 0;
            /* To add new Assets objects against original OpportunityLineItem-ID as key */
            Map<ID, Asset> assetObjMap = new Map<ID, Asset>();
            for (Opportunity oppty: actionableOpptyDetailsMap.values()) {  
                if (rAppSetup.Asset__c == True) {
                    OpportunityRenewalHelper.setAssetsLineItemOfOpportunity(oppty, assetObjMap, availableAssetObjMap);
                } 
                //Applying entitlement template setting from product set-up tied to opportunity product line
                //calculating entitlement start date, term, end date
                //creating 'YYYYMM' key for each source opportunity line item based on calculated entitlement end date
                //passing Product2Map to read renewal term from it
                Map<String, Map<String, OpportunityLineItem>> splitedLineItemMap =  OpportunityRenewalHelper.getSplitedLineItemMap(oppty, product2Map); 

                //START: - Data setup for selected OpportunityLineItems 
                //for each distinct 'YYYYMM' key from opp line items, a separate renewal opp will be created            
                for (Map<String, OpportunityLineItem> renewableOpptyLineItemBunch: splitedLineItemMap.values()) {
                    //creating oppRenewalWrapper which contains Opportunity Obj, List of OppLineItems, ServiceContract Obj
                    //list of entitlement, list of service contract line items
                    OpportunityRenewalWrapper oppRenewalWrapper = null;
                    try {
                        oppRenewalWrapper = OpportunityRenewalHelper.getRenewableLineItemWithOpportunity(
                            renewableOpptyLineItemBunch, new List<Opportunity>{oppty}, product2Map, renewableOpptysAccountMap, rAppSetup, assetObjMap);
                    } catch(InvalidOperationException e) {
                        if (actionableOpptyDetailsMap.size() == 1) {
                            throw e;
                        } 
                    }
                    if (oppRenewalWrapper == null) {
                        continue;
                    }
                    //Set all the data in opptyRenewalWrapperMap for later use.
                    if (oppRenewalWrapper.opportunityObj != null) {
                        opptyRenewalWrapperMap.put(''+iCount, oppRenewalWrapper);
                        renewedOpptyMap.put(''+iCount, oppRenewalWrapper.opportunityObj);
                        iCount++;   
                    }
                }
                //END: - Data setup for selected OpportunityLineItems 
            }
            //END: - Data setup for bulk process, 
            // No records found for new renewable.
            system.debug('renewedOpptyMap:'+renewedOpptyMap);
            if (renewedOpptyMap.size() == 0) {
                return; 
            } 
            upsert renewedOpptyMap.values();
            List <OpportunityTeamMember> bulkListOpportunityTeamMember = new List<OpportunityTeamMember>();
            List <OpportunityPartner> bulkListOpportunityPartner = new List<OpportunityPartner>();
            List <OpportunityContactRole> bulkListOpportunityContactRole = new List<OpportunityContactRole>();
            List <OpportunityCompetitor> bulkListOpportunityCompetitor = new List<OpportunityCompetitor>();

system.debug('renewedOpptyMap::'+renewedOpptyMap);
            List<ID> OpportunityIDs = new List<ID>();
            //Step-50 + 60: Create old and new Opportunities mapping
            for (String iCounter: renewedOpptyMap.keySet()) {
                Opportunity renewedOpty = renewedOpptyMap.get(iCounter);
                OpportunityIDs.add(renewedOpty.Id);
                System.debug('\n\n' + iCounter + '.~~~~SUCCESS: Renewed Opportunity created: ' + renewedOpty.Name);
                
                /* Create a list for Source-Renewed-Oppty-Mapping-List */
                //it's not an add-on
system.debug('renewedOpty::'+renewedOpty);                
                if (renewedOpty.Co_Term_With__c == NULL) {
system.debug('opt::1');                    
                    sourceRenewedOpptyMappingList.add(
                        new Source_Opp_Mapping__c(
                                Source_Opp__c = renewedOpty.Originating_Opportunity__c, 
                                Renewal_Opp__c = renewedOpty.ID
                        )
                    ); 
                    sourceRenewedOpptyMappingList.add(
                        new Source_Opp_Mapping__c(
                                Source_Opp__c = renewedOpty.ID, 
                                Renewal_Opp__c = renewedOpty.Originating_Opportunity__c
                        )
                    ); 
                } else {
system.debug('opt::2');                                        
                    sourceRenewedOpptyMappingList.add(
                        new Source_Opp_Mapping__c(
                                Source_Opp__c = renewedOpty.Originating_Opportunity__c, 
                                Renewal_Opp__c = renewedOpty.ID
                        )
                    ); 
                    sourceRenewedOpptyMappingList.add(
                        new Source_Opp_Mapping__c(
                                Source_Opp__c = renewedOpty.ID, 
                                Renewal_Opp__c = renewedOpty.Originating_Opportunity__c
                        )
                    );                 
                }

                //create opportunity line items. Link OppLineItems to respective opportunity object created earlier
                List<OpportunityLineItem> opportunityLineItemObjList = opptyRenewalWrapperMap.get(iCounter).opportunityLineItemObjList;
                If (opportunityLineItemObjList != NULL && opportunityLineItemObjList.size() > 0){
                    for (OpportunityLineItem lItem : opportunityLineItemObjList) {
                        If (renewedOpty.ID != NULL && lItem.Id == NULL) {
                            lItem.OpportunityId=renewedOpty.ID;
                        }
                        //OpportunityLineItem List
                        renewedOpptyProductList.add(lItem);
                    }
                }               
system.debug('actionableOpptyDetailsMap::'+actionableOpptyDetailsMap);
system.debug('actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c)::'+actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c));
                //Create Assets
                OpportunityRenewalHelper.reSetAssetsLineItemOfOpportunity(actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c),renewedOpty,assetObjMap, product2Map);
                
                //Cloning related lists
                if (rAppSetup.Clone_Opp_Team_Related_List__c) {
                   OpportunityRenewalHelper.setClonedOpportunityTeamMembers(actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c),renewedOpty,bulkListOpportunityTeamMember);
                }
                //if (rAppSetup.Clone_Partner_Related_List__c) {
                    //OpportunityRenewalHelper.setClonedOpportunityPartners(actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c),renewedOpty,bulkListOpportunityPartner);
                //}
                if (rAppSetup.Clone_Contact_Roles__c) {
                    OpportunityRenewalHelper.setClonedOpportunityContactRoles(actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c),renewedOpty,bulkListOpportunityContactRole);
                }
                if (rAppSetup.Clone_Competitors_Related_List__c) {
                    OpportunityRenewalHelper.setClonedOpportunityCompetitors(actionableOpptyDetailsMap.get(renewedOpty.Originating_Opportunity__c),renewedOpty,bulkListOpportunityCompetitor);
                }               
            }

            system.debug('sourceRenewedOpptyMappingList::'+sourceRenewedOpptyMappingList);
            insert sourceRenewedOpptyMappingList;
            // OpportunityLineItem
            upsert renewedOpptyProductList; 
            if (bulkListOpportunityTeamMember.size() > 0) {
                insert bulkListOpportunityTeamMember;
            }
            if (bulkListOpportunityContactRole.size() > 0) {
                insert bulkListOpportunityContactRole;
            }
            if (bulkListOpportunityCompetitor.size() > 0) {
                insert bulkListOpportunityCompetitor;
            }

            Map<ID, Opportunity> OppAmountListMap = new Map<ID, Opportunity>([Select Id, Amount From Opportunity Where Id In :OpportunityIDs]);
            
            List<OpportunityLineItem> AllLineItemsOfOpp = new List<OpportunityLineItem>([Select Id, OpportunityId, UnitPrice, Quantity, Sales_Price_Per_Unit_Per_Ent_Term__c, Entitlement_Term__c, Product_Entitlement_Term_Set_Up__c, Discount, TotalPrice From OpportunityLineItem Where OpportunityId In :OpportunityIDs]);
            Map<ID, OpportunityLineItem> AllLineItemsOfOppMap = new Map<ID, OpportunityLineItem>();
            for (OpportunityLineItem OL : AllLineItemsOfOpp){
                AllLineItemsOfOppMap.put(OL.OpportunityId, OL);
            }
            system.debug('All Line Item ' + AllLineItemsOfOpp);
            // Adding below logic to set Base_Line_Amount on renewal opportunity to Amount so that upgrade/downgrade logic works on renewal opp
            // Reason for adding this at end of this flow here so that OpportunityLineItem trigger also does it's magic to calculate pro-rate price and all
            for (String iCounter: renewedOpptyMap.keySet()) {
        /*        decimal baselineamount = 0.00;
                if (renewedOpptyMap.get(iCounter).Base_Line_Amount__c != NULL) {
                    baselineamount = renewedOpptyMap.get(iCounter).Base_Line_Amount__c;
                }*/
              
                for (OpportunityLineItem BaseLineOppList : renewedOpptyProductList) {
                    if (BaseLineOppList.Opportunity_LineItem_ID__c != null && assetObjMap.containsKey(BaseLineOppList.Opportunity_LineItem_ID__c)) {
                        //Reset new OLI.
                        assetObjMap.get(BaseLineOppList.Opportunity_LineItem_ID__c).Originating_LineItem_ID__c = BaseLineOppList.ID;
                    }
                    
                 /*   if (BaseLineOppList.OpportunityId == renewedOpptyMap.get(iCounter).ID) {
                        decimal LineItemTotal = 0.00;
                        If (BaseLineOppList.Product_Entitlement_Term_Set_Up__c == NULL) {
                               LineItemTotal = BaseLineOppList.UnitPrice * BaseLineOppList.Quantity;
                        } else { 
                        LineItemTotal = BaseLineOppList.UnitPrice * BaseLineOppList.Quantity * (BaseLineOppList.Entitlement_Term__c / BaseLineOppList.Product_Entitlement_Term_Set_Up__c ); // * BaseLineOppList.Sales_Price_Per_Unit_Per_Ent_Term__c * (BaseLineOppList.Entitlement_Term__c / BaseLineOppList.Product_Entitlement_Term_Set_Up__c ); // BaseLineOppList.UnitPrice;
                        }
                        system.debug('LineItemTotal:  ' + LineItemTotal);
                        if ( BaseLineOppList.Discount != NULL) {
                            baselineamount += LineItemTotal * ((100 - BaseLineOppList.Discount)/100);
                        } else {
                            baselineamount += LineItemTotal;
                            system.debug('baselineamount :  ' + baselineamount );
                        }               
                    }*/
                } 
                system.debug('Amount 123 ' + renewedOpptyMap.get(iCounter).Amount);
                decimal baselineamount = 0.00;
                for (OpportunityLineItem OL : AllLineItemsOfOpp){
                    system.debug('OppID ' + renewedOpptyMap.get(iCounter).Id);
                    system.debug('Opp Line Item ID ' + OL.Id);
                    If (OL.OpportunityId == renewedOpptyMap.get(iCounter).Id){
                        baselineamount += OL.Quantity * OL.UnitPrice * (OL.Entitlement_Term__c / OL.Product_Entitlement_Term_Set_Up__c );
                        system.debug('Base Line Amount1 ' + baselineamount);
                    }                
                }
                system.debug('Base Line Amount ' + baselineamount);
                renewedOpptyMap.get(iCounter).Base_Line_Amount__c = OppAmountListMap.get(renewedOpptyMap.get(iCounter).Id).Amount; //baselineamount; //renewedOpptyMap.get(iCounter).Amount; //baselineamount; 
            }
            //re-run it in order to update Base_Line_Amount field in opportunity entry    
            upsert renewedOpptyMap.values(); 
             
            if (assetObjMap.size() > 0) {
                system.debug('asset object map in trigger  '  + assetObjMap);
                upsert assetObjMap.values();
            }
            Map<ID, OpportunityLineItem> oliMap = new Map<ID, OpportunityLineItem>(renewedOpptyProductList);
            oliMap = new Map<ID, OpportunityLineItem>([SELECT ID, Opportunity_LineItem_ID__c from OpportunityLineItem where Opportunity_LineItem_ID__c != NULL AND ID in : oliMap.keySet()]);
            List<OpportunityLineItem> updateOpportunityLineItemWithAssetList = new List<OpportunityLineItem>();
            for (OpportunityLineItem newProduct : oliMap.values()) {
                if (assetObjMap.containsKey(newProduct.Opportunity_LineItem_ID__c)) {
                    newProduct.Asset__c = assetObjMap.get(newProduct.Opportunity_LineItem_ID__c).ID;
                    updateOpportunityLineItemWithAssetList.add(newProduct);
                }
            }
            if (updateOpportunityLineItemWithAssetList.size() > 0) {
                update updateOpportunityLineItemWithAssetList;
            }
        } catch (DmlException e) {
            System.debug('~~~~~~~~~~Error-1:' + e.getMessage());
            throw e;
        } catch (InvalidOperationException e) {
            System.debug(actionableOpptyDetailsMap.size() + '\n\n~~~~~~~~~~ERROR-2:' + e.getMessage());
            if (newOpptyList.size() == 1) {
                newOpptyList.get(0).addError(' Please make sure that source opportunity with which this add-on is co-termed with is closed and renewal opp created from closure of source opp has not been deleted.');
                System.debug('~~~~~~~~~~ERROR-21:' + actionableOpptyDetailsMap);
            }
        } catch (Exception e) {
            System.debug('~~~~~~~~~~ERROR-3:' + e.getMessage());
             throw e;
        }  
    }
}