src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Source_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Opp_Record_Type_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Renewal_Opp_Record_Type_ID__c</fullName>
        <description>Stores ID of Renewal Opp Record Type</description>
        <inlineHelpText>Stores ID of Renewal Opp Record Type</inlineHelpText>
        <label>Renewal Opp Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Opp_Record_Type_Name__c</fullName>
        <description>Stores Name of Renewal Opp Record Type</description>
        <inlineHelpText>Stores Name of Renewal Opp Record Type</inlineHelpText>
        <label>Renewal Opp Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Opp_Record_Type_ID__c</fullName>
        <description>Stores ID of Source Opp Record Type</description>
        <inlineHelpText>Stores ID of Source Opp Record Type</inlineHelpText>
        <label>Source Opp Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Opp_Record_Type_Name__c</fullName>
        <description>Stores Name of Source Opp Record Type</description>
        <inlineHelpText>Stores Name of Source Opp Record Type</inlineHelpText>
        <label>Source Opp Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opp Record Type Mapping</label>
    <nameField>
        <label>Opp Record Type Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opp Record Type Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Co_Term_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Original opp with which products from these opp are co-termed.</description>
        <inlineHelpText>Original sales opportunity with which products on this opportunity should be co-termed.</inlineHelpText>
        <label>Co-Term With</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>CoTermOpp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Add_on_Opportunity__c</fullName>
        <inlineHelpText>New sales opportunity for an existing customer that is independent of renewal process</inlineHelpText>
        <label>Is Add-on Opportunity?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <businessProcess>CD_Sales Process</businessProcess>
        <label>test</label>
    </recordTypes>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProRate_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check here if you want to allow pro-rating of prices for this product based. E.g. If price set-up is $1200 for one year subscription and when it is sold for 3 month subscription, pro-rated price on opportunity line item would be 1200 * (3/12) = $300.</description>
        <inlineHelpText>Check here if you want to allow pro-rating of prices for this product based. E.g. If price set-up is $1200 for one year subscription and when it is sold for 3 month subscription, pro-rated price on opportunity line item would be 1200 * (3/12) = $300.</inlineHelpText>
        <label>Can the price be pro-rated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Term_Months__c</fullName>
        <inlineHelpText>Number of months after which this product would be renewed.</inlineHelpText>
        <label>Renewal Term (Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Use_this_same_product_in_Renewal_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to use this same product while creating Renewal Opportunity.</description>
        <inlineHelpText>Check this box when you want to use this same product while creating Renewal Opportunity.</inlineHelpText>
        <label>Use this same product in Renewal Opp</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Renewal_App_Setup__c.object
<CustomObject>
    <label>Renewal App Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Renewal App Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal App Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityLineItemFieldUpdatesTest.cls
@isTest (seeAllData = true)
private class OpportunityLineItemFieldUpdatesTest {

    static testMethod void testUpdateParentAccount() {
        // Create configuration data.
        Renewal_App_Setup__c renewalAppSetupRec = TestHelper.getRenewalAppSetup();
        upsert renewalAppSetupRec;

        // Set up Opportunity Record first
        Date OppCloseDate = Date.newinstance(2012, 12, 01);
        String OppName = 'Test Opportunity for Trigger Test';
        String OppStage = 'Prospecting';

        Account acc = new Account(Name = 'Teradata International');
        insert acc;

        Opportunity o = new Opportunity(AccountID = acc.Id, Name = OppName,  StageName = OppStage, CloseDate = OppCloseDate); //'005E000000DIQnIAK',);
        insert o;

        //set up Product record
        string ProductName = 'Lotus 123';
        string ProductDescription = 'Lotus Notes Description';
        Decimal RenewalTerm = 12.0;
        Product2 Prod = new Product2(Name = ProductName, Description = ProductDescription, use_this_same_product_in_renewal_opp__c = true, prorate_price__c = true, renewal_term_months__c = RenewalTerm, isactive = true);
        insert Prod;

        //insert standard price for product
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard = true limit 1];
        Decimal StdPrice = 10.00;
        PriceBookEntry PBEntry1 = new PriceBookEntry(UnitPrice = StdPrice, PriceBook2Id = standardPB.Id, Product2ID = Prod.Id, IsActive = true, UseStandardPrice = false);
        insert PBEntry1;

        //insert OppLineItem
        OpportunityLineItem Opp = new OpportunityLineItem(UnitPrice = StdPrice , Quantity = 5.0, PricebookEntryId = PBEntry1.Id, OpportunityId = o.Id);
        insert Opp;

        //Making product renewable to test further
        Prod.use_this_same_product_in_renewal_opp__c = true;
        upsert Prod;
        Opp.Description = NULL;
        upsert Opp;

        upsert Prod;
        Opp.Description = NULL;
        upsert Opp;

        //having mark up being entered and cost coming from product set up
        Decimal MarkUp = 100;
        //Opp.Mark_up__c = MarkUp;
        upsert Opp;
        //entering user entered cost as well
        Decimal Cost = 500;
        upsert Opp;

        //doing co-term check
        Opportunity CoTermOpp = new Opportunity(AccountID = acc.Id, Name = OppName,  StageName = OppStage, CloseDate = OppCloseDate, Co_Term_With__c = o.Id, Is_Add_on_Opportunity__c = 'yes');
        insert CoTermOpp;
        //insert OppLineItem
        OpportunityLineItem coTermOppLineItem = new OpportunityLineItem(UnitPrice = StdPrice , Quantity = 5.0, PricebookEntryId = PBEntry1.Id, OpportunityId = CoTermOpp.Id);
        insert coTermOppLineItem ;
        // insert Asset record to test out AssetHistoryTrigger
        Asset AssetObj = new Asset( Name = Prod.Name , Source_Opp__c = o.Id, Product2Id = Prod.Id, Quantity = 5, Price = 100.00, AccountId = o.AccountId, InstallDate = system.today());
        insert AssetObj;
        AssetObj.Quantity = 10;
        Upsert AssetObj;

        //insert Opp Record Type and Test OppRecordTypeMappingDML
        RecordType r = [Select Id, Description, Name From RecordType Where  IsActive = true limit 1];

        Opp_Record_Type_Mapping__c oppRec;
        oppRec = new Opp_Record_Type_Mapping__c(Renewal_Opp_Record_Type_ID__c = r.Id, Renewal_Opp_Record_Type_Name__c = 'Test', Source_Opp_Record_Type_ID__c = r.Id, Source_Opp_Record_Type_Name__c = 'Test');
        insert OppRec;
        system.assertEquals(oppRec.Source_Opp_Record_Type_Name__c, 'Test');
    }
}