src/objects/Opp_Record_Type_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Renewal_Opp_Record_Type_ID__c</fullName>
        <description>Stores ID of Renewal Opp Record Type</description>
        <inlineHelpText>Stores ID of Renewal Opp Record Type</inlineHelpText>
        <label>Renewal Opp Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Opp_Record_Type_Name__c</fullName>
        <description>Stores Name of Renewal Opp Record Type</description>
        <inlineHelpText>Stores Name of Renewal Opp Record Type</inlineHelpText>
        <label>Renewal Opp Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Opp_Record_Type_ID__c</fullName>
        <description>Stores ID of Source Opp Record Type</description>
        <inlineHelpText>Stores ID of Source Opp Record Type</inlineHelpText>
        <label>Source Opp Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Opp_Record_Type_Name__c</fullName>
        <description>Stores Name of Source Opp Record Type</description>
        <inlineHelpText>Stores Name of Source Opp Record Type</inlineHelpText>
        <label>Source Opp Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opp Record Type Mapping</label>
    <nameField>
        <label>Opp Record Type Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opp Record Type Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Co_Term_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Original opp with which products from these opp are co-termed.</description>
        <inlineHelpText>Original sales opportunity with which products on this opportunity should be co-termed.</inlineHelpText>
        <label>Co-Term With</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>CoTermOpp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Contact1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Term_Expiration_Date__c</fullName>
        <inlineHelpText>Date by which customers right to use the products expire if the renewal opportunity is not closed won.</inlineHelpText>
        <label>Original Term Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ready_For_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this opportunity ready for creation of renewal opportunity? If so, check this box and Renewal Manager App will auto create renewal opportunity as this opportunity is won.</inlineHelpText>
        <label>Renewal Needed and Ready for It</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Upgrade_Downgrade_Amount__c</fullName>
        <formula>Amount - Base_Line_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a difference between renewal opportunity amount and the base line amount.</inlineHelpText>
        <label>Upgrade/Downgrade Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upgrade_Downgrade_Reason__c</fullName>
        <label>Upgrade/Downgrade Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Service upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-year contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied with product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied with service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not in budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Switched to competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not in use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of business/divestiture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Upgrade_Downgrade__c</fullName>
        <description>Indicates that the renewal is an upgrade or downgrade from original customer purchase.</description>
        <formula>IF(AND(NOT(ISNULL(Amount)),NOT(ISNULL(Base_Line_Amount__c)) ), 
IF( Amount &gt; Base_Line_Amount__c ,
&quot;Upgrade&quot; ,
IF(Amount &lt; Base_Line_Amount__c,
&quot;Downgrade&quot;, &quot;&quot;) )
,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates that the renewal is an upgrade or downgrade from original customer purchase.</inlineHelpText>
        <label>Upgrade/Downgrade?</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset of this line item</description>
        <inlineHelpText>Asset of this line item</inlineHelpText>
        <label>Asset tied to this line item</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entitlement_End_Date__c</fullName>
        <description>Enter entitlement end date</description>
        <inlineHelpText>Enter entitlement end date</inlineHelpText>
        <label>Entitlement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entitlement_Start_Date__c</fullName>
        <description>Enter entitlement start date</description>
        <inlineHelpText>Enter entitlement start date</inlineHelpText>
        <label>Entitlement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_LineItem_ID__c</fullName>
        <label>Originating Opportunity LineItem ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_LineItem_URL__c</fullName>
        <label>Originating Opportunity LineItem</label>
        <type>Url</type>
    </fields>
</CustomObject>

src/objects/Renewal_App_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If your organization is using asset while verifying entitlements in support cases then check this box to auto convert products on &apos;closed won&apos; opportunities into Asset. Default status on converted asset will be &apos;shipped&apos;.</description>
        <inlineHelpText>If your organization is using asset while verifying entitlements in support cases then check this box to auto convert products on &apos;closed won&apos; opportunities into Asset. Default status on converted asset will be &apos;shipped&apos;.</inlineHelpText>
        <label>Convert Product into Asset of Won Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Competitors_Related_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Competitor Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Competitor Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Competitors Related List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Contact_Roles__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Contact Roles Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Contact Roles Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Contact Roles</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Opp_Team_Related_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Opportunity Team Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Opportunity Team Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Opp Team Related List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Field_To_Not_Copy_on_Renewal__c</fullName>
        <description>Select the fields that need not be copied while Opportunity is cloned to create Renewal Opp.</description>
        <inlineHelpText>Select the fields that need not be copied while Opportunity is cloned to create Renewal Opp.</inlineHelpText>
        <label>Opportunity Field To Not Copy on Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>null</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Fields_To_Not_Copy__c</fullName>
        <description>Select the fields that need not be copied while Opportunity Products of source opportunity are cloned to create Renewal Opp.</description>
        <inlineHelpText>Select the fields that need not be copied while Opportunity Products of source opportunity are cloned to create Renewal Opp.</inlineHelpText>
        <label>Opportunity Product Fields To Not Copy</label>
        <picklist>
            <picklistValues>
                <fullName>null</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Prefix_for_Renewal_Opportunity_Name__c</fullName>
        <defaultValue>&quot;Renewal&quot;</defaultValue>
        <description>Sufffix for Renewal Opportunity. Original source opportunity would be suffixed with text entered here to create opportunity name of Renewal Opportunity. E.g. Text entered in this field is &apos;Renewal &apos; and name of original source opportunity is &apos;Software Support Purchase&apos; then name of Renewal Opportunity would be &apos;Software Support Purchase : Renewal - 10/2013&apos;. 10/2013 indicates month and year renewal is due.</description>
        <inlineHelpText>Original source opp would be suffixed with text entered here to create opportunity name of Renewal Opportunity.</inlineHelpText>
        <label>Suffix for Renewal Opportunity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Owner__c</fullName>
        <description>Pick to whom Renewal Opportunity should be assigned.</description>
        <inlineHelpText>Pick to whom Renewal Opportunity should be assigned.</inlineHelpText>
        <label>Renewal Opportunity Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Same as Source Opportunity Owner</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Account Owner of Acct tied to Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A specific User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Type__c</fullName>
        <description>A &apos;Type&apos; field&apos;s value of the Renewal Opportunity.
Must be equal to one of the picklist values of the &apos;Type&apos; field of opportunity</description>
        <inlineHelpText>A Type field&apos;s value of the Renewal Opportunity.
Must be equal to one of the picklist values of the &apos;Type&apos; field of opportunity
Normal value is &apos;Existing Customer - Renewal&apos;</inlineHelpText>
        <label>Renewal Opportunity Type</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Stage__c</fullName>
        <description>First default stage of the Renewal Opportunity.
Normally is &apos;Prospecting&apos;. Picklist is ordered in ascending default probability of stage.</description>
        <inlineHelpText>First default stage of the Renewal Opportunity.
Normally is &apos;Prospecting&apos;. Picklist is ordered in ascending default probability of stage.</inlineHelpText>
        <label>Renewal Opportunity Default Stage</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pick the user to whom Renewals should get assigned.</description>
        <inlineHelpText>Pick the user to whom Renewals should get assigned.</inlineHelpText>
        <label>Assign Renewal to</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Renewal_App_Set</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal App Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Renewal App Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal App Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RenewalAppSetupController.cls
/**
 * Copyright (c) 2014 Comity Designs
 * All rights reserved.
 *
 * This class is controller class for the Renewal Manager configuration page.
 *
 * History:
 * =========================================
 * Developer         Date        description
 * --------------------------------------------------------------------------------------------------
 * Ivan Melnikov     07/30/2014  Code refactoring 
 *
 * 
 **/
public with sharing class RenewalAppSetupController {
       
    public Renewal_App_Setup__c renewalSetupObject;
    public Boolean showSaveMessage {get; set;}
        
    public Set<String> SetUnselectedOpptyFields = new Set<String>();
    public Set<String> SetSelectedOpptyFields = new Set<String> ();
    public List<String> selectedOpptyFields {get; set; }
    public List<String> unselectedOpptyFields {get; set; }
    
    public List<Opp_Record_Type_Mapping__c> oppRecTypeMappingList {get; set;}
    public List<RecordType> oppRecTypeList {get; set;}
    
    public Set<String> SetUnselectedOpptyLIFields = new Set<String>();
    public Set<String> SetSelectedOpptyLIFields = new Set<String> ();
    public List<String> selectedOpptyLIFields {get; set;}
    public List<String> unselectedOpptyLIFields {get; set;}
    
    public Map<String, String> mapOpptyNameLabel = new Map<String, String>();  
    public Map<String, String> mapOpptyLINameLabel = new Map<String, String>();
    private Boolean isValid = true; 
    
    /** Constructor */    
    public RenewalAppSetupController() {
        this.oppRecTypeMappingList = getOpportunityRecordTypeMapping();
    }
    
    private class CustomFieldsIds {
        public String customFieldId {get; set;}
    } 

    /**
     * @description     Initialize configuration data.
     */
    public void init() {
        this.getRenewalSetupObject();
        this.retrieveOpptyFields();
        this.retrieveOpptyLIFields();
    }

    public List<Opp_Record_Type_Mapping__c> getOpportunityRecordTypeMapping() {
        Map<ID, RecordType> recordTypeMap = new Map<ID, RecordType>([
            SELECT  r.SobjectType, r.Name, r.IsActive, r.Id, r.Description 
            FROM RecordType r 
            WHERE r.SobjectType = 'Opportunity' and  r.IsActive = true
        ]);
        
        List<Opp_Record_Type_Mapping__c> oppRecTypeMappingList = [
            SELECT id, Source_Opp_Record_Type_ID__c, Source_Opp_Record_Type_Name__c, Renewal_Opp_Record_Type_ID__c, 
                Renewal_Opp_Record_Type_Name__c, Name 
            FROM Opp_Record_Type_Mapping__c
            LIMIT :Limits.getLimitQueryRows()];
        this.oppRecTypeList = recordTypeMap.values();
        Integer iCount = -1;

        Map<ID, Opp_Record_Type_Mapping__c> oppRecTypeMappingMap = new Map<ID, Opp_Record_Type_Mapping__c>();
        
        System.debug(recordTypeMap.keySet()+ '\n\n~~~~10: ' + oppRecTypeMappingList);
        
        //Sync existing record type
        for (Opp_Record_Type_Mapping__c m : oppRecTypeMappingList) {
            iCount++;
            if (recordTypeMap.containsKey(m.Source_Opp_Record_Type_ID__c)) {
                m.Name = recordTypeMap.get(m.Source_Opp_Record_Type_ID__c).Name;
                m.Source_Opp_Record_Type_Name__c = recordTypeMap.get(m.Source_Opp_Record_Type_ID__c).Description;
                if (recordTypeMap.containsKey(m.Renewal_Opp_Record_Type_ID__c)) {
                    m.Renewal_Opp_Record_Type_Name__c = recordTypeMap.get(m.Renewal_Opp_Record_Type_ID__c).Name;
                } else {
                    m.Renewal_Opp_Record_Type_ID__c = m.Source_Opp_Record_Type_ID__c;
                    m.Renewal_Opp_Record_Type_Name__c = m.Name;
                }
                oppRecTypeMappingMap.put(m.Source_Opp_Record_Type_ID__c, m);
            }
        }
        System.debug(oppRecTypeMappingMap.keySet()+ '\n\n~~~~11: ' + recordTypeMap.keySet());
        
        //Add additional Record Type.
        for (RecordType rec : recordTypeMap.values()) {
            if (!oppRecTypeMappingMap.containsKey(rec.ID)) {
                Opp_Record_Type_Mapping__c m = new Opp_Record_Type_Mapping__c();
                m.Name = rec.Name;
                m.Source_Opp_Record_Type_ID__c = rec.id;
                m.Source_Opp_Record_Type_Name__c = rec.Description;
                m.Renewal_Opp_Record_Type_ID__c = m.Source_Opp_Record_Type_ID__c;
                m.Renewal_Opp_Record_Type_Name__c = m.Name;
                oppRecTypeMappingList.add(m);
            }
        }
        return oppRecTypeMappingList;
    }

    public List<SelectOption> OpportunityRecordTypeList { 
        get {
          list<SelectOption> options = new list<SelectOption>();
          for (RecordType rec : this.oppRecTypeList) { 
             options.add(new SelectOption(rec.ID,rec.Name)); 
          }
          return options;
        }
    }    
    
    public Renewal_App_Setup__c getRenewalSetupObject() {
 
        if (this.renewalSetupObject == null) {
            Renewal_App_Setup__c[] tmpSetupAr = [
                SELECT r.Renewal_Stage__c, r.Renewal_Opportunity_Type__c,  r.Prefix_for_Renewal_Opportunity_Name__c,
                    r.Asset__c, r.Opportunity_Field_To_Not_Copy_on_Renewal__c, r.Opportunity_Product_Fields_To_Not_Copy__c,
                    r.Renewal_Opportunity_Owner__c, r.User__c, r.Clone_Competitors_Related_List__c, r.Clone_Contact_Roles__c, 
                    r.Clone_Opp_Team_Related_List__c
            FROM Renewal_App_Setup__c r
            LIMIT :Limits.getLimitQueryRows()];
                                                      
            if (tmpSetupAr.size() == 1) {
                this.renewalSetupObject = tmpSetupAr[0];
            } else if (tmpSetupAr.size() == 0) {
                this.renewalSetupObject = new Renewal_App_Setup__c();
            } else if (tmpSetupAr.size() > 1) {
                this.setIsValid(false);
                this.addError(RenewalLabelsAndMessages.ERROR_INVALID_RENEWAL_APP_SETUP);
                for (Renewal_App_Setup__c tmpSetup : tmpSetupAr) {
                    this.addError('Record Id: ' + tmpSetup.Id);
                }
            } 
        }
        return this.renewalSetupObject;     
    }
    
    //save button
    public PageReference save() {
        String Opportunity_Field_To_Not_Copy_on_Renewal = '';
        String Opportunity_Product_Fields_To_Not_Copy = '';
        List<String> LSelectedOpptyFields = new List<String>();
        List<String> LSelectedOpptyLIFields = new List<String>();
        LSelectedOpptyFields.addAll(SetSelectedOpptyFields);
        Opportunity_Field_To_Not_Copy_on_Renewal = String.join(LSelectedOpptyFields, ';'); 
        renewalSetupObject.Opportunity_Field_To_Not_Copy_on_Renewal__c = Opportunity_Field_To_Not_Copy_on_Renewal ;
        LSelectedOpptyLIFields.addAll(SetSelectedOpptyLIFields);
        Opportunity_Product_Fields_To_Not_Copy = String.join(LSelectedOpptyLIFields, ';'); 
        renewalSetupObject.Opportunity_Product_Fields_To_Not_Copy__c = Opportunity_Product_Fields_To_Not_Copy ;
        if (renewalSetupObject.Renewal_Opportunity_Owner__c == 'A specific User') {
            if (renewalSetupObject.User__c == null) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please pick the user to whom renewal should get assigned.'));
                return null;
            }
        } else {
            renewalSetupObject.User__c = null;
        }
        upsert renewalSetupObject;
       
        List<Renewal_App_Setup__c> tempCheckList = new List<Renewal_App_Setup__c>([
            SELECT r.Opportunity_Field_To_Not_Copy_on_Renewal__c, r.Opportunity_Product_Fields_To_Not_Copy__c
            FROM Renewal_App_Setup__c r 
            LIMIT 1
        ]);      
        
        if (oppRecTypeMappingList != null && oppRecTypeMappingList.size() > 0) {
            upsert oppRecTypeMappingList;
        }
        
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Confirm, 'Renewal App Setup saved successfully.'));
        return null;
    }
    
    //cancel button
    public PageReference cancel() {
        PageReference cancelPage = new PageReference(RenewalLabelsAndMessages.homePageUrl);
        cancelPage.setRedirect(true);       
        return cancelPage;
    }
    
    public void setIsValid(Boolean b) {
        this.isValid = b;
    }
    
    public Boolean getIsValid() {
        return this.isValid;
    }   
    
        //Method adds an error message to the page
    private void addError(String errorMsg) {         
        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,errorMsg);               
        ApexPages.addMessage(msg);
    }
    
    private void retrieveOpptyFields() {
        map<String, Schema.SobjectField> AllOpptyFields = Schema.SobjectType.Opportunity.fields.getMap();
        List<String> ListSelectedOpptyRecsInObj = new List<String>();
        map<String, String> mapSelectedOpptyRecsInObj = new map<String, String>();
        for (Schema.SobjectField sfield : AllOpptyFields.Values()) {
            String tempName;
            schema.describefieldresult dfield = sfield.getDescribe();
            tempName = dfield.getName();
            mapOpptyNameLabel.put(tempName.toLowerCase(), dfield.getLabel());                       
        }
        
        if (renewalSetupObject != null) {
            if (renewalSetupObject.Opportunity_Field_To_Not_Copy_on_Renewal__c != null) {
                String chosenOpportunity_Fields = renewalSetupObject.Opportunity_Field_To_Not_Copy_on_Renewal__c;
                ListSelectedOpptyRecsInObj = chosenOpportunity_Fields.split(';', -1);
            }
        }
        
        if (!ListSelectedOpptyRecsInObj.isEmpty()) {
            for (String s : ListSelectedOpptyRecsInObj) {
                mapSelectedOpptyRecsInObj.put(s.toLowerCase(), s);
            }
        }
        
        for (String s : AllOpptyFields.keySet()) {
            if (!mapSelectedOpptyRecsInObj.isEmpty()) {
                if (mapSelectedOpptyRecsInObj.containsKey(s.toLowerCase())) {
                    SetSelectedOpptyFields.add(s);
                } else {
                    SetUnselectedOpptyFields.add(s);
                }
            } else {
                SetUnselectedOpptyFields.add(s);
            }
            
        }
        //removing below set of fields from available list as these are set while renewal opp is created
        SetUnselectedOpptyFields.remove('ready_for_renewal__c');
        SetUnselectedOpptyFields.remove('name');  
        SetUnselectedOpptyFields.remove('type');
        SetUnselectedOpptyFields.remove('stagename');
        SetUnselectedOpptyFields.remove('closedate');
        SetUnselectedOpptyFields.remove('contact__c');
        SetUnselectedOpptyFields.remove('ownerid');
        SetUnselectedOpptyFields.remove('recordtypeid');
        SetUnselectedOpptyFields.remove('co_term_with__c');
        SetUnselectedOpptyFields.remove('original_term_expiration_date__c ');
        SetUnselectedOpptyFields.remove('id');      
        SetUnselectedOpptyFields.remove('pricebook2id');
        SetUnselectedOpptyFields.remove('upgrade_downgrade_reason__c');
        SetUnselectedOpptyFields.remove('upgrade_downgrade_amount__c');
        SetUnselectedOpptyFields.remove('upgrade_downgrade__c'); 
        
    }

    public List<SelectOption> selectedOptionsOpptyFields { 
        get {
            List<String> sorted = new List<String>(SetSelectedOpptyFields);
            sorted.sort();
            List<SelectOption> options = new List<SelectOption>();
            for (String s : sorted) {
                if (mapOpptyNameLabel.get(s.toLowerCase()) != null) {
                    options.add(new SelectOption(s, mapOpptyNameLabel.get(s.toLowerCase())));
                }
            }
            return options;
        }
    }

    public List<SelectOption> unSelectedOptionsOpptyFields { 
        get {
            List<String> sorted = new List<String>(SetUnselectedOpptyFields);
            sorted.sort();
            List<SelectOption> options = new List<SelectOption>();
            system.debug('mapOpptyNameLabel::'+mapOpptyNameLabel);
            for (String s : sorted) {
                system.debug('s::'+mapOpptyNameLabel);
                if (mapOpptyNameLabel.get(s.toLowerCase()) != null) {
                    options.add(new SelectOption(s, mapOpptyNameLabel.get(s.toLowerCase())));
                }
            }
            return options;
        }
    }
    
    public void doSelectOpptyFields() {
        if (!selectedOpptyFields.isEmpty()) {
            for (String s: selectedOpptyFields) {
                SetSelectedOpptyFields.add(s);
                SetUnselectedOpptyFields.remove(s);
            }
        }
    }
    
    public void doUnSelectOpptyFields() {
        if (!unselectedOpptyFields.isEmpty()) {
            for (String s: unselectedOpptyFields) {
                SetUnselectedOpptyFields.add(s);
                SetSelectedOpptyFields.remove(s);
            }
        }
    }  
    
    private void retrieveOpptyLIFields() {
        
        map<String, Schema.SobjectField> AllOpptyLIFields = Schema.SobjectType.OpportunityLineItem.fields.getMap(); 
        List<String> ListSelectedOpptyLIRecsInObj = new List<String>();  
        map<String, String> mapSelectedOpptyLIRecsInObj = new map<String, String>(); 
        
        for (Schema.SobjectField sfield : AllOpptyLIFields.Values()) {
            String tempName;
            schema.describefieldresult dfield = sfield.getDescribe();
            tempName = dfield.getName();
            mapOpptyLINameLabel.put(tempName.toLowerCase(), dfield.getLabel());              
        }
                
        if (renewalSetupObject != null) {
            if (renewalSetupObject.Opportunity_Product_Fields_To_Not_Copy__c != null) {
                String chosenOpportunityLI_Fields = renewalSetupObject.Opportunity_Product_Fields_To_Not_Copy__c;
                ListSelectedOpptyLIRecsInObj = chosenOpportunityLI_Fields.split(';', -1);
            }
        }
        
        if (!ListSelectedOpptyLIRecsInObj.isEmpty()) {
            for (String s : ListSelectedOpptyLIRecsInObj) {
                mapSelectedOpptyLIRecsInObj.put(s.toLowerCase(), s);
            }
        }
        
        for (String s : AllOpptyLIFields.keySet()) {
            if (!mapSelectedOpptyLIRecsInObj.isEmpty()) {
                if (mapSelectedOpptyLIRecsInObj.containsKey(s.toLowerCase())) {
                    SetSelectedOpptyLIFields.add(s);  
                } else {
                    SetUnselectedOpptyLIFields.add(s);  
                }
            } else {
                SetUnselectedOpptyLIFields.add(s);  
            }
        }
        //removing below set of fields from available list as these are set while renewal opp is created
        SetUnselectedOpptyLIFields.remove('totalprice');
        SetUnselectedOpptyLIFields.remove('opportunity_lineitem_id__c');
        SetUnselectedOpptyLIFields.remove('opportunity_lineitem_url__c');
        SetUnselectedOpptyLIFields.remove('commision_percentage__c');
        SetUnselectedOpptyLIFields.remove('entitlement_start_date__c');
        SetUnselectedOpptyLIFields.remove('entitlement_end_date__c');
        SetUnselectedOpptyLIFields.remove('servicedate');
        SetUnselectedOpptyLIFields.remove('unitprice');
    }

    public List<SelectOption> selectedOptionsOpptyLIFields { 
        get {
            List<String> sorted = new List<String>(SetSelectedOpptyLIFields);
            sorted.sort();
            List<SelectOption> options = new List<SelectOption>();
            for (String s : sorted) {
                if (mapOpptyLINameLabel.get(s.toLowerCase()) != null) {
                    options.add(new SelectOption(s, mapOpptyLINameLabel.get(s.toLowerCase())));
                }
            }
            return options;
        }
    }

    public List<SelectOption> unSelectedOptionsOpptyLIFields { 
        get {
            List<String> sorted = new List<String>(SetUnselectedOpptyLIFields);
            sorted.sort();
            List<SelectOption> options = new List<SelectOption>();
            for (String s : sorted) {
                if (mapOpptyLINameLabel.get(s.toLowerCase()) != null) {
                    options.add(new SelectOption(s, mapOpptyLINameLabel.get(s.toLowerCase())));
                }
            }
            return options;
        }
    }

    public List<SelectOption> OpportunityStageList { 
        get {
            List<OpportunityStage> OppStageList = new List<OpportunityStage>([
                SELECT MasterLabel 
                FROM OpportunityStage 
                ORDER BY DefaultProbability ASC, MasterLabel ASC
                LIMIT :Limits.getLimitQueryRows()
            ]);
            List<SelectOption> options = new List<SelectOption>();
            for (OpportunityStage s : OppStageList) {
                options.add(new SelectOption(s.MasterLabel, s.MasterLabel));
            }
            return options;
        }
    }

    public List<SelectOption> OpportunityTypeList { 
        get {
          list<SelectOption> options = new list<SelectOption>();
          // Get the object type of the SObject.
          Schema.sObjectType objType = Opportunity.getSObjectType(); 
          // Describe the SObject using its object type.
          Schema.DescribeSObjectResult objDescribe = objType.getDescribe();       
          // Get a map of fields for the SObject
          map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap(); 
          // Get the list of picklist values for this field.
          list<Schema.PicklistEntry> values =
             fieldMap.get('Type').getDescribe().getPickListValues();
          // Add these values to the selectoption list.
          for (Schema.PicklistEntry a : values) { 
             options.add(new SelectOption(a.getLabel(), a.getValue())); 
          }
          return options;
        }
    }    
            
    public void doSelectOpptyLIFields() {
        for (String s: selectedOpptyLIFields) {
            SetSelectedOpptyLIFields.add(s);
            SetUnselectedOpptyLIFields.remove(s);
        }
    }
    
    public void doUnSelectOpptyLIFields() {
        for (String s: unselectedOpptyLIFields) {
            SetUnselectedOpptyLIFields.add(s);
            SetSelectedOpptyLIFields.remove(s);
        }
    }
}