src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>CD_Sales</fullName>
        <active>true</active>
        <businessProcess>CD_Sales Process</businessProcess>
        <description>Record Type for Sales Opportunities</description>
        <label>CD_Sales</label>
    </recordTypes>
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <businessProcess>CD_Sales Process</businessProcess>
        <label>test</label>
    </recordTypes>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset of this line item</description>
        <inlineHelpText>Asset of this line item</inlineHelpText>
        <label>Asset tied to this line item</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProRate_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check here if you want to allow pro-rating of prices for this product based. E.g. If price set-up is $1200 for one year subscription and when it is sold for 3 month subscription, pro-rated price on opportunity line item would be 1200 * (3/12) = $300.</description>
        <inlineHelpText>Check here if you want to allow pro-rating of prices for this product based. E.g. If price set-up is $1200 for one year subscription and when it is sold for 3 month subscription, pro-rated price on opportunity line item would be 1200 * (3/12) = $300.</inlineHelpText>
        <label>Can the price be pro-rated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Term_Months__c</fullName>
        <inlineHelpText>Number of months after which this product would be renewed.</inlineHelpText>
        <label>Renewal Term (Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Use_this_same_product_in_Renewal_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to use this same product while creating Renewal Opportunity.</description>
        <inlineHelpText>Check this box when you want to use this same product while creating Renewal Opportunity.</inlineHelpText>
        <label>Use this same product in Renewal Opp</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Renewal_App_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If your organization is using asset while verifying entitlements in support cases then check this box to auto convert products on &apos;closed won&apos; opportunities into Asset. Default status on converted asset will be &apos;shipped&apos;.</description>
        <inlineHelpText>If your organization is using asset while verifying entitlements in support cases then check this box to auto convert products on &apos;closed won&apos; opportunities into Asset. Default status on converted asset will be &apos;shipped&apos;.</inlineHelpText>
        <label>Convert Product into Asset of Won Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Competitors_Related_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Competitor Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Competitor Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Competitors Related List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Contact_Roles__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Contact Roles Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Contact Roles Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Contact Roles</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clone_Opp_Team_Related_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if Opportunity Team Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</description>
        <inlineHelpText>Check this box if Opportunity Team Related List is to be cloned as well onto renewal opportunity while cloning source opportunity to create renewal opportunity.</inlineHelpText>
        <label>Clone Opp Team Related List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Field_To_Not_Copy_on_Renewal__c</fullName>
        <description>Select the fields that need not be copied while Opportunity is cloned to create Renewal Opp.</description>
        <inlineHelpText>Select the fields that need not be copied while Opportunity is cloned to create Renewal Opp.</inlineHelpText>
        <label>Opportunity Field To Not Copy on Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>null</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Fields_To_Not_Copy__c</fullName>
        <description>Select the fields that need not be copied while Opportunity Products of source opportunity are cloned to create Renewal Opp.</description>
        <inlineHelpText>Select the fields that need not be copied while Opportunity Products of source opportunity are cloned to create Renewal Opp.</inlineHelpText>
        <label>Opportunity Product Fields To Not Copy</label>
        <picklist>
            <picklistValues>
                <fullName>null</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Prefix_for_Renewal_Opportunity_Name__c</fullName>
        <defaultValue>&quot;Renewal&quot;</defaultValue>
        <description>Sufffix for Renewal Opportunity. Original source opportunity would be suffixed with text entered here to create opportunity name of Renewal Opportunity. E.g. Text entered in this field is &apos;Renewal &apos; and name of original source opportunity is &apos;Software Support Purchase&apos; then name of Renewal Opportunity would be &apos;Software Support Purchase : Renewal - 10/2013&apos;. 10/2013 indicates month and year renewal is due.</description>
        <inlineHelpText>Original source opp would be suffixed with text entered here to create opportunity name of Renewal Opportunity.</inlineHelpText>
        <label>Suffix for Renewal Opportunity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Owner__c</fullName>
        <description>Pick to whom Renewal Opportunity should be assigned.</description>
        <inlineHelpText>Pick to whom Renewal Opportunity should be assigned.</inlineHelpText>
        <label>Renewal Opportunity Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Same as Source Opportunity Owner</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Account Owner of Acct tied to Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A specific User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Type__c</fullName>
        <description>A &apos;Type&apos; field&apos;s value of the Renewal Opportunity.
Must be equal to one of the picklist values of the &apos;Type&apos; field of opportunity</description>
        <inlineHelpText>A Type field&apos;s value of the Renewal Opportunity.
Must be equal to one of the picklist values of the &apos;Type&apos; field of opportunity
Normal value is &apos;Existing Customer - Renewal&apos;</inlineHelpText>
        <label>Renewal Opportunity Type</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Stage__c</fullName>
        <description>First default stage of the Renewal Opportunity.
Normally is &apos;Prospecting&apos;. Picklist is ordered in ascending default probability of stage.</description>
        <inlineHelpText>First default stage of the Renewal Opportunity.
Normally is &apos;Prospecting&apos;. Picklist is ordered in ascending default probability of stage.</inlineHelpText>
        <label>Renewal Opportunity Default Stage</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pick the user to whom Renewals should get assigned.</description>
        <inlineHelpText>Pick the user to whom Renewals should get assigned.</inlineHelpText>
        <label>Assign Renewal to</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Renewal_App_Set</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal App Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Renewal App Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal App Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestHelper.cls
/**
 * Copyright (c) 2014 Comity Designs
 * All rights reserved.
 *
 * This is test helper class contains methods for test classes of Renewal manager.
 *
 * History:
 * =========================================
 * Developer         Date        description
 * --------------------------------------------------------------------------------------------------
 * Ivan Melnikov     07/30/2014  Code refactoring 
 *
 * 
 **/
public with sharing class TestHelper {

    public static final String PRICEBOOK_NAME = 'Default pricebook name';
    public static final String OPPORTUNITY_NAME = 'Default Oppty Name';
    public static final String OPPORTUNITY_OPEN_STAGE = 'Prospecting';
    public static final String OPPORTUNITY_CLOSED_STAGE = 'Closed Won';

    public static final String PRODUCT_NAME = 'Default Product Name';
    public static final String PRODUCT_DESCRIPTION = 'Default Product description';
    public static final Decimal PRODUCT_RENEWAL_TERM = 12.0;
    public static final Decimal PRODUCT_STANDARD_UNIT_PRICE = 12.0;
    
    public static final Decimal OLI_QUANTITY = 5;

    public static final String ACCOUNT_NAME = 'Org Test Account';

    public static final String RENEWAL_APP_SETUP_RENEWAL_OPPTY_TYPE_EXISITING = 'Existing Customer - Renewal';
    public static final String RENEWAL_APP_SETUP_RENEWAL_OPPTY_STAGE = 'Needs Analysis';

    // Configuration data, should exist only one record.
    private static Renewal_App_Setup__c renewalAppSetup;
    public static Renewal_App_Setup__c getRenewalAppSetup() {
        List<Renewal_App_Setup__c> renewalAppSetupList = [
            SELECT User__c, Clone_Competitors_Related_List__c, Clone_Contact_Roles__c, Clone_Opp_Team_Related_List__c,
                Asset__c, Opportunity_Field_To_Not_Copy_on_Renewal__c, Opportunity_Product_Fields_To_Not_Copy__c,
                Renewal_Stage__c, Renewal_Opportunity_Owner__c, Renewal_Opportunity_Type__c, Prefix_for_Renewal_Opportunity_Name__c
            FROM Renewal_App_Setup__c 
            LIMIT 1
        ];

        if (!renewalAppSetupList.isEmpty()) {
            renewalAppSetup = renewalAppSetupList[0];
        } else {
            renewalAppSetup = new Renewal_App_Setup__c(
                Renewal_Stage__c = RENEWAL_APP_SETUP_RENEWAL_OPPTY_STAGE,
                Renewal_Opportunity_Type__c = RENEWAL_APP_SETUP_RENEWAL_OPPTY_TYPE_EXISITING
            );
        }
        return renewalAppSetup;
    }

    public static Account getDefaultAccount() {
        return new Account(Name = ACCOUNT_NAME);
    }

    public static Contact getDefaultContact(Id accountId) {
        return new Contact(AccountId = accountId,
            LastName = 'Test',
            FirstName = 'Test');
    }

    public static Opportunity getDefaultOpenOpportunity(Id accountId) {
        	List<RecordType> RL = new List<RecordType>([Select Id, Name From RecordType Where Name = 'CD_Sales' LIMIT 1]);
        	ID CDSalesRecordTypeID = RL[0].Id;
        	
        return new Opportunity(
            AccountId = accountId, 
            Name = OPPORTUNITY_NAME,
            StageName = OPPORTUNITY_OPEN_STAGE, 
            RecordTypeId = CDSalesRecordTypeID,
            CloseDate = Date.today()
        );
    }

    public static OpportunityLineItem getDefaultOpportunityLineItem(Id opptyId, Id pricebookEntryId) {
        return new OpportunityLineItem(
            UnitPrice = PRODUCT_STANDARD_UNIT_PRICE, 
            Quantity = OLI_QUANTITY, 
            PricebookEntryId = pricebookEntryId, 
            OpportunityId = opptyId
        );
    }

    public static Product2 getRenewalProduct() {
        return new Product2(
            Name = PRODUCT_NAME, 
            Description = PRODUCT_DESCRIPTION,
            use_this_same_product_in_renewal_opp__c = true, 
            prorate_price__c = true, 
            renewal_term_months__c = PRODUCT_RENEWAL_TERM, 
            isactive = true
        );

    }

    public static PricebookEntry getDefaultPricebookEntry(Id productId) {
        return new PricebookEntry(
            UnitPrice = PRODUCT_STANDARD_UNIT_PRICE, 
            PriceBook2Id = Test.getStandardPricebookId(), 
            Product2ID = productId, 
            IsActive = true, 
            UseStandardPrice = false
        );
    }
}