src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Co_Term_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Original opp with which products from these opp are co-termed.</description>
        <inlineHelpText>Original sales opportunity with which products on this opportunity should be co-termed.</inlineHelpText>
        <label>Co-Term With</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>CoTermOpp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Contact1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Add_on_Opportunity__c</fullName>
        <inlineHelpText>New sales opportunity for an existing customer that is independent of renewal process</inlineHelpText>
        <label>Is Add-on Opportunity?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originating_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to an Originating Opportunity for Renewal Opportunity</description>
        <inlineHelpText>Original sales opportunity that was the basis for the renewal opportunity</inlineHelpText>
        <label>Originating Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Originating Opportunity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <businessProcess>CD_Sales Process</businessProcess>
        <label>test</label>
    </recordTypes>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Originating_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Originating Source Opportunity ID from where renewal opportunity was created. This is to be used while updating renewal opp when source opp is updated. Example, renewal opp had 50 quantities on certain product from source opp and later on source opp got updated to 55 quantities of same product. This field will allow to update renewal opp easily.</description>
        <label>Originating Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProRate_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check here if you want to allow pro-rating of prices for this product based. E.g. If price set-up is $1200 for one year subscription and when it is sold for 3 month subscription, pro-rated price on opportunity line item would be 1200 * (3/12) = $300.</description>
        <inlineHelpText>Check here if you want to allow pro-rating of prices for this product based. E.g. If price set-up is $1200 for one year subscription and when it is sold for 3 month subscription, pro-rated price on opportunity line item would be 1200 * (3/12) = $300.</inlineHelpText>
        <label>Can the price be pro-rated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_To_Use_In_Renewal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pick different product to be added to renewal opportunity when application creates renewal opportunity when this product is part of source opportunity.</description>
        <inlineHelpText>Pick different product to be added to renewal opportunity when application creates renewal opportunity when this product is part of source opportunity.</inlineHelpText>
        <label>Pick Different Product to use in Renewal</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Supporting_Products_in_Renewal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Term_Months__c</fullName>
        <inlineHelpText>Number of months after which this product would be renewed.</inlineHelpText>
        <label>Renewal Term (Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Use_this_same_product_in_Renewal_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to use this same product while creating Renewal Opportunity.</description>
        <inlineHelpText>Check this box when you want to use this same product while creating Renewal Opportunity.</inlineHelpText>
        <label>Use this same product in Renewal Opp</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Renewal_App_Setup__c.object
<CustomObject>
    <label>Renewal App Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Renewal App Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal App Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Source_Opp_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Renewal_Opp__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <formula>Renewal_Opp__r.CloseDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source/Renewal Opp</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal/Source Opp Mappings</relationshipLabel>
        <relationshipName>Renewal_Opp_Mappings_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Opp</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Source/Renewal Opp Mappings</relationshipLabel>
        <relationshipName>Source_Opp_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Source/Renewal Opp Mapping</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Source Opp Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source/Renewal Opp Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerTest.cls
/**
 * Copyright (c) 2014 Comity Designs
 * All rights reserved.
 *
 * This class is test class for the Opportunity trigger.
 *
 * History:
 * =========================================
 * Developer         Date        description
 * --------------------------------------------------------------------------------------------------
 * Ivan Melnikov     07/30/2014  Code refactoring 
 *
 * 
 **/
@isTest (seeAllData = true)
private class OpportunityTriggerTest {
    static testMethod void testSameProductbeingRenewable() {
        // Create configuration data.
        Renewal_App_Setup__c renewalAppSetupRec = TestHelper.getRenewalAppSetup();
        upsert renewalAppSetupRec;

        Account acc = TestHelper.getDefaultAccount();
        insert acc;

        Opportunity  baseOppty = TestHelper.getDefaultOpenOpportunity(acc.Id);
        insert baseOppty;

        system.debug('baseOppty::'+baseOppty);

        Product2 prod = TestHelper.getRenewalProduct();
        insert prod;

        PriceBookEntry pbEntry = TestHelper.getDefaultPricebookEntry(prod.Id);
        insert pbEntry;

        OpportunityLineItem oli = TestHelper.getDefaultOpportunityLineItem(baseOppty.Id, pbEntry.Id);
        insert oli;

        // Close opportunity.
        baseOppty.StageName = TestHelper.OPPORTUNITY_CLOSED_STAGE;

        Test.startTest();
        upsert baseOppty;
        Test.stopTest();

        // Validate that mapping records has been created.
        List<Source_Opp_Mapping__c> sourceOppMappingList = [
            SELECT Source_Opp__c, Renewal_Opp__c, Account_Name__c, Close_Date__c
            FROM Source_Opp_Mapping__c
            WHERE Source_Opp__c = : baseOppty.Id
        ];
        System.assertEquals(sourceOppMappingList.size(),1);
        // TODO: how close date is getting set?
        //System.assertEquals(sourceOppMappingList[0].Close_Date__c, baseOppty.CloseDate); 
        System.assertEquals(sourceOppMappingList[0].Account_Name__c, acc.Name);

        sourceOppMappingList = [
            SELECT Source_Opp__c, Renewal_Opp__c, Account_Name__c, Close_Date__c
            FROM Source_Opp_Mapping__c
            WHERE Renewal_Opp__c = : baseOppty.Id
        ];
        System.assertEquals(sourceOppMappingList.size(),1);
        // TODO: how close date is getting set?
        //System.assertEquals(sourceOppMappingList[0].Close_Date__c, baseOppty.CloseDate);
        System.assertEquals(sourceOppMappingList[0].Account_Name__c, acc.Name);

        // Validate that new renewal opportunity has been created.
        List<Opportunity> renewalOpptyList = [
            SELECT Originating_Opportunity__c 
            FROM Opportunity 
            WHERE Originating_Opportunity__c = :baseOppty.Id    
        ];
        System.assertEquals(renewalOpptyList.size(), 1);
    }

    static testMethod void testDifferentProductbeingRenewable() {

        Account acc = TestHelper.getDefaultAccount();
        insert acc;

        Opportunity  baseOppty = TestHelper.getDefaultOpenOpportunity(acc.Id);
        insert baseOppty;

        Product2 prod = TestHelper.getRenewalProduct();
        insert prod;

        Product2 prod2 = TestHelper.getRenewalProduct();
        prod2.Product_To_Use_In_Renewal__c = prod.id;
        prod2.Use_this_same_product_in_Renewal_Opp__c = false;        
        insert prod2;        

        PriceBookEntry pbEntry = TestHelper.getDefaultPricebookEntry(prod2.Id);
        insert pbEntry;

        OpportunityLineItem oli = TestHelper.getDefaultOpportunityLineItem(baseOppty.Id, pbEntry.Id);
        insert oli;

        // Close opportunity.
        baseOppty.StageName = TestHelper.OPPORTUNITY_CLOSED_STAGE;

        Test.startTest();
        upsert baseOppty;
        Test.stopTest();

        // Validate results.
        // Validate that mapping records has NOT been created.
        List<Source_Opp_Mapping__c> sourceOppMappingList = [
            SELECT Source_Opp__c, Renewal_Opp__c, Account_Name__c, Close_Date__c
            FROM Source_Opp_Mapping__c
            WHERE Source_Opp__c = : baseOppty.Id
        ];
        System.assertEquals(sourceOppMappingList.size(), 0);        
    }

    static testMethod void testCoTermOpp() {

        Account acc = TestHelper.getDefaultAccount();
        insert acc;

        Opportunity  baseOppty = TestHelper.getDefaultOpenOpportunity(acc.Id);
        insert baseOppty;

        Product2 prod = TestHelper.getRenewalProduct();
        insert prod;

        Product2 prod2 = TestHelper.getRenewalProduct();
        prod2.Product_To_Use_In_Renewal__c = prod.id;
        prod2.Use_this_same_product_in_Renewal_Opp__c = false;        
        insert prod2; 

        PriceBookEntry pbEntry = TestHelper.getDefaultPricebookEntry(prod2.Id);
        insert pbEntry;

        OpportunityLineItem oli = TestHelper.getDefaultOpportunityLineItem(baseOppty.Id, pbEntry.Id);
        insert oli;

        // Close opportunity.
        baseOppty.StageName = TestHelper.OPPORTUNITY_CLOSED_STAGE;

        upsert baseOppty;

        // Insert co-term oppty.
        Opportunity coTermOppty = TestHelper.getDefaultOpenOpportunity(acc.Id);
        coTermOppty.Co_Term_With__c = baseOppty.Id; 
        coTermOppty.Is_Add_on_Opportunity__c = 'yes';
        insert coTermOppty;

        // Insert OppLineItem for CoTerm
        OpportunityLineItem cotermOli = TestHelper.getDefaultOpportunityLineItem(coTermOppty.Id, pbEntry.Id);
        insert cotermOli;

        // Close coTermOppty.
        coTermOppty.StageName = TestHelper.OPPORTUNITY_CLOSED_STAGE;

        Test.startTest();
        upsert coTermOppty;
        Test.stopTest();

        // Verify results.
        // Validate that mapping records has NOT been created.
        List<Source_Opp_Mapping__c> sourceOppMappingList = [
            SELECT Source_Opp__c, Renewal_Opp__c, Account_Name__c, Close_Date__c
            FROM Source_Opp_Mapping__c
            WHERE Source_Opp__c = : baseOppty.Id
        ];
        System.assertEquals(sourceOppMappingList.size(), 0);  
    }

    static testMethod void testEntitlementContact() {    
       
          // Set up Opportunity Record first
        Date OppCloseDate = Date.newinstance(2012,12,01);
        String OppName = 'Test Opportunity for Trigger Test';
        String OppStage = 'Prospecting';

        Account Acc = new Account(Name='Org Test Account');
        insert Acc;

        Contact c = TestHelper.getDefaultContact(Acc.Id);
        insert c;
                        
        Opportunity o = new Opportunity(AccountID=Acc.Id, Name=OppName,  StageName=OppStage, CloseDate=OppCloseDate, Contact__c = c.Id); //'005E000000DIQnIAK',);
        insert o;

        //set up Product record
        String ProductName = 'Lotus 123';
        String ProductDescription = 'Lotus Notes Description';   
        Decimal RenewalTerm = 12.0;   
        Product2 Prod = new Product2(Name=ProductName, Description=ProductDescription, use_this_same_product_in_renewal_opp__c = true, prorate_price__c = true, renewal_term_months__c = RenewalTerm, isactive = true);
        insert Prod;

        Product2 Prod2 = new Product2(Name='XYZ-1', Description=ProductDescription, use_this_same_product_in_renewal_opp__c = true, prorate_price__c = true, renewal_term_months__c = RenewalTerm, isactive = true);
        insert Prod2;
          
        Prod.Product_To_Use_In_Renewal__c = Prod2.id;
        Prod.Use_this_same_product_in_Renewal_Opp__c = false;
        upsert Prod;

        Decimal StdPrice = 10.00;
        PriceBookEntry PBEntry1 = new PriceBookEntry(UnitPrice=StdPrice, PriceBook2Id=Test.getStandardPricebookId(), Product2ID=Prod.Id, IsActive = true, UseStandardPrice = false);
        insert PBEntry1;      
          
        //insert OppLineItem
        OpportunityLineItem Opp = new OpportunityLineItem(UnitPrice=StdPrice , Quantity=5.0, PricebookEntryId=PBEntry1.Id, OpportunityId=o.Id);
        insert Opp;
          
          
        o.StageName = 'Closed Won';
        upsert o;

        // Validate that mapping records has NOT been created.
        List<Source_Opp_Mapping__c> sourceOppMappingList = [
            SELECT Source_Opp__c, Renewal_Opp__c, Account_Name__c, Close_Date__c
            FROM Source_Opp_Mapping__c
            WHERE Source_Opp__c = : o.Id
        ];
        System.assertEquals(sourceOppMappingList.size(), 0);          
      }    
}